<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar el partido final?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'partidofinal', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<div class="col_6">
<a href="<?php echo $this->url(array('controller' => 'partidofinal',
            'action' => 'crear')); ?>">Crear nuevo Partido Final</a>
	<h4>Partido Final</h4>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Jugador uno</th>
            <th>Jugador dos</th>
            <th>Juez</th>
            <th>Torneo</th>
            <th>Puntos</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>                
                <td><?php echo $this->escape($d->_id); ?></td>
                <!--            nombre del album, con un enlace para editar el album-->
                <td>
                <?php
                $datos1 = Application_Model_Jugador::find($d->jugadoruno);
                if($datos1=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos1->nombre);
                ?>
                </td>
                <!--                        descripcion-->
                <td>
                <?php
                $datos2 = Application_Model_Jugador::find($d->jugadordos);
                if($datos2=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos2->nombre);
                ?>
                </td>
                <!--                        descripcion-->
                <td>
                <?php
                $datos3 = Application_Model_Juez::find($d->juez);
                if($datos3=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos3->nombre);
                ?>
                </td>
                <td>
                <?php
                $datos4 = Application_Model_Torneo::find($d->torneo);
                if($datos4=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos4->nombre);
                ?>
                </td>
                
                <td><a href="<?php echo $this->url(array('controller' => 'partidofinal', 'action' => 'mostrar', '_id' => $d->_id)); ?>">Puntos_del_Partido</a></td>
                <!--                   enlace para borrar el album-->
                <td><a href="<?php  echo $this->url(array('controller' => 'partidofinal', 'action' => 'modificar', '_id' => $d->_id)); ?>"><span title="Editar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/pencil.png" /></span></a>&nbsp;&nbsp;  
                    <a onclick="confirmDelete('<?php echo $d->_id; ?>')" >  <span title="Eliminar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/minus.png" /></span></a> 
                </td>
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>
</div>