<div class="col_9">
<a>Puntos Partido Final - Set 1</a>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th colspan="2">Game 1</th>
            <th colspan="2">Game 2</th>
            <th colspan="2">Game 3</th>
            <th colspan="2">Game 4</th>
            <th colspan="2">Game 5</th>
            <th colspan="2">Game 6</th>
        </tr>
        <tr>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
        </tr>
        
    </thead>
    <tbody>
            <tr>
                <td><?php echo $this->escape($this->d->puntosjugadoruno1set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos1set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno2set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos2set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno3set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos3set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno4set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos4set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno5set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos5set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno6set1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos6set1); ?></td>                
            </tr>
    </tbody>
</table>
</div>
<br><br>
<div class="col_9">
<a>Puntos Partido Final - Set 2</a>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th colspan="2">Game 1</th>
            <th colspan="2">Game 2</th>
            <th colspan="2">Game 3</th>
            <th colspan="2">Game 4</th>
            <th colspan="2">Game 5</th>
            <th colspan="2">Game 6</th>
        </tr>
        <tr>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
        </tr>
        
    </thead>
    <tbody>
            <tr>
                <td><?php echo $this->escape($this->d->puntosjugadoruno1set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos1set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno2set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos2set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno3set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos3set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno4set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos4set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno5set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos5set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno6set2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos6set2); ?></td>                
            </tr>
    </tbody>
</table>
</div>
<br><br>
<div class="col_9">
<a>Puntos Partido Final - Set 3</a>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th colspan="2">Game 1</th>
            <th colspan="2">Game 2</th>
            <th colspan="2">Game 3</th>
            <th colspan="2">Game 4</th>
            <th colspan="2">Game 5</th>
            <th colspan="2">Game 6</th>
        </tr>
        <tr>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
            <th>Jugador1</th><th>Jugador2</th>
        </tr>
        
    </thead>
    <tbody>
            <tr>
                <td><?php echo $this->escape($this->d->puntosjugadoruno1set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos1set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno2set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos2set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno3set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos3set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno4set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos4set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno5set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos5set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno6set3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos6set3); ?></td>                
            </tr>
    </tbody>
</table>
</div>