<?php echo $this->form; ?>

<table class="sortable">
    <thead>
        <tr>            
            <th>Nombre</th>            
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->dato as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <?php                                
                if(is_int($d->_id))
                {    
                    $var=0;
                }    
                else
                {    
                    $datos = Application_Model_Pareja::find($d->pareja);
                    if($datos=="")
                        $var = "Ninguno";
                    else
                    {  
                        $dato = Application_Model_Pareja::find($d->pareja);
                        $dato1 = Application_Model_Jugador::find($dato->jugadoruno);
                        $dato2 = Application_Model_Jugador::find($dato->jugadordos);
                        $var = $dato1->nombre.' - '.$dato2->nombre;
                    }    
                }
                if(is_string($var)) {?>
                <tr><td><?php echo $this->escape($var); }?></td></tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>

<?php  
$table = Application_Model_Programarjugador::one();
$dato = $table->torneo;
?>
<center><a href="<?php echo $this->url(array('controller' => 'torneo', 'action' => 'programargrupojugador', '_id' => $dato)); ?>"><button>Asignar Jugador a Grupo</button></a></center>