<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar el juez?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'juez', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<div class="col_6">
<a href="<?php echo $this->url(array('controller' => 'juez',
            'action' => 'crear')); ?>">Crear nuevo Juez</a>
	<h4>Jueces</h4>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Documento</th>
            <th>Experiencia</th>
            <th>Torneo</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>
                <td><?php echo $this->escape($d->_id); ?></td>
                <!--            nombre del album, con un enlace para editar el album-->
                <td><a href="<?php echo $this->url(array('controller' => 'juez', 'action' => 'modificar', '_id' => $d->_id)); ?>"><?php echo $d->nombre; ?></a></td>
                <!--                id del artista-->
                <td><?php echo $this->escape($d->documento); ?></td>
                <!--                    fecha del album-->
                <td><?php echo $this->escape($d->experiencia); ?></td>
                <!--                        descripcion-->
                <td>
                <?php
                $datos1 = Application_Model_Torneo::find($d->torneo);
                if($datos1=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos1->nombre);
                ?>
                </td>
                <!--                   enlace para borrar el album-->

                <td><a href="<?php  echo $this->url(array('controller' => 'juez', 'action' => 'modificar', '_id' => $d->_id)); ?>"><span title="Editar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/pencil.png" /></span></a>&nbsp;&nbsp;  
                    <a onclick="confirmDelete('<?php echo $d->_id; ?>')" >  <span title="Eliminar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/minus.png" /></span></a> 
                </td>
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>
</div>