<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar la categoria?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'categoria', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<a href="<?php echo $this->url(array('controller' => 'categoria',
            'action' => 'crear')); ?>">Crear nueva Categoria</a>


<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>            
            <th>Nombre</th>
            <th>Valor Inscripcion</th>
            <th>Torneo</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>
                <td><?php echo $this->escape($d->_id); ?></td>
                <!--            nombre del album, con un enlace para editar el album-->
                <td><a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'editar', '_id' => $d->_id)); ?>"><?php echo $d->nombre; ?></a></td>
                <!--                id del artista-->
                <td><?php echo $this->escape($d->valorinscripcion); ?></td>
                <!--                        descripcion-->
                <td><?php echo $this->escape($d->torneo); ?></td>
                <!--                   enlace para borrar el album-->
                <td><a href=href="#" onclick="confirmDelete('<?php echo $d->_id; ?>')"><span class="icon gray" data-icon="7"></span></a> <a href="<?php // echo $this->url(array('controller' => 'categoria', 'action' => 'editar', '_id' => $d->_id)); ?>"><span class="icon gray" data-icon="m"></span></a></td>
                
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>