<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!--        referencia al archivo css, uso $this->baseUrl para tener una referencia segun
        el lugar dede donde se llame al layout-->
        <link href="<?php echo $this->baseUrl; ?>/zendwww/public/css/estilos.css" type="text/css" rel="stylesheet">
          <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/javascript/jquery/jquery-1.4.2.min.js"></script>
        
    </head>
    <body>
        <div class="banner">
<!--           imagen, tambien uso $this->baseUrl para referenciarla-->
            <img src="<?php echo $this->baseUrl; ?>/zendwww/public/images/header.jpg" width="1200" height="150" alt="header"/>
        </div>
        <h1><?php echo $this->title; ?></h1>

        <h3>Este es el contenido de la vista:</h3>
        <div class="contenido">
<!--            muestro el contenido segun la vista-->
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
