<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar el grupo?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'grupo', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<a href="<?php echo $this->url(array('controller' => 'grupo',
            'action' => 'crear')); ?>">Crear nuevo Grupo</a>


<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Num. de Integrantes</th>            
            <th>Torneo</th>
            <th>Ronda</th>
            <th>Cancha</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>
                <td><?php echo $this->escape($d->_id); ?></td>
                <!--            nombre del album, con un enlace para editar el album-->
                <td><a href="<?php echo $this->url(array('controller' => 'grupo', 'action' => 'modificar', '_id' => $d->_id)); ?>"><?php echo $d->nombre; ?></a></td>
                <!--                id del artista-->
                <td><?php echo $this->escape($d->numintegrantes); ?></td>
                <!--                    fecha del album-->
                <td><?php echo $this->escape($d->torneo); ?></td>
                <!--                        descripcion-->
                <td><?php echo $this->escape($d->ronda); ?></td>
                <!--                        descripcion-->
                <td><?php echo $this->escape($d->cancha); ?></td>
                <!--                   enlace para borrar el album-->
                    <td><a href="#" onclick="confirmDelete('<?php echo $d->_id; ?>')">Eliminar</a>


                </td>
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>