<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar la programacion?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'programacion', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<div class="col_6">
<a href="<?php echo $this->url(array('controller' => 'programacion',
            'action' => 'crear')); ?>">Crear nueva Programacion</a>
	<h4>Programacion</h4>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Grupo</th>
            <th>Cancha</th>            
            <th>Fecha</th>
            <th>Hora</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>
                <td><?php echo $this->escape($d->_id); ?></td>
                <!--            nombre del album, con un enlace para editar el album-->
                <td>
                <?php
                $datos1 = Application_Model_Grupo::find($d->grupo);
                if($datos1=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos1->nombre);
                ?>
                </td>
                <!--                    fecha del album-->
                <!--                        descripcion-->
                <td>
                <?php
                $datos2 = Application_Model_Canchas::find($d->cancha);
                if($datos2=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos2->nombre);
                ?>
                </td>
                
                <td><?php echo $this->escape($d->fecha); ?></td>
                <td><?php echo $this->escape($d->hora); ?></td>
                <!--                        descripcion-->                
                <td><a href="<?php  echo $this->url(array('controller' => 'programacion', 'action' => 'modificar', '_id' => $d->_id)); ?>"><span title="Editar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/pencil.png" /></span></a>&nbsp;&nbsp;  
                    <a onclick="confirmDelete('<?php echo $d->_id; ?>')" >  <span title="Eliminar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/minus.png" /></span></a> 
                </td>
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>
</div>