<!DOCTYPE html>
<html>

  <head>
    <title>www</title> 
 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" />
    </head>

<body> 


<div data-role="page" id="login" data-title="Login">
    <div data-role="header" data-theme="c">
        <h1>Iniciar Sesi&oacute;n</h1>
        <a href="#home" data-icon="home" data-iconpos="notext" class="ui-btn-right"></a>
    </div><!-- /header -->
 
    <div data-role="content" data-theme="c">
    
        <form action="#" method="post" id="login">           
	  <div data-role="controlgroup">
           	      
	      <a href="<?php echo $this->url(array('controller' => 'partido',
            'action' => 'partidonorm')); ?>" data-role="button">PARTIDO</a>
	      <a href="<?php echo $this->url(array('controller' => 'partido',
            'action' => 'partidofinal')); ?>" data-role="button">PARTIDO FINAL</a>
	     
	  </div>	
      </form>
    </div><!-- /content -->
 
    <div data-role="footer" data-theme="c">
        <h4>&copy; </h4>
    </div><!-- /footer -->
</div><!-- /page login -->


</body> 
    

</html>