
<script language="Javascript" type="text/javascript">
function refreshDivs(divid,secs,url)
{

// define our vars
var divid,secs,url,fetch_unix_timestamp;

// Chequeamos que las variables no esten vacias..
if(divid == ""){ alert('Error: escribe el id del div que quieres refrescar'); return;}
else if(!document.getElementById(divid)){ alert('Error: el Div ID selectionado no esta definido: '+divid); return;}
else if(secs == ""){ alert('Error: indica la cantidad de segundos que quieres que el div se refresque'); return;}
else if(url == ""){ alert('Error: la URL del documento que quieres cargar en el div no puede estar vacia.'); return;}

// The XMLHttpRequest object

var xmlHttp;
try{
xmlHttp=new XMLHttpRequest(); // Firefox, Opera 8.0+, Safari
}
catch (e){
try{
xmlHttp=new ActiveXObject("Msxml2.XMLHTTP"); // Internet Explorer
}
catch (e){
try{
xmlHttp=new ActiveXObject("Microsoft.XMLHTTP");
}
catch (e){
alert("Tu explorador no soporta AJAX.");
return false;
}
}
}

// Timestamp para evitar que se cachee el array GET

fetch_unix_timestamp = function()
{
return parseInt(new Date().getTime().toString().substring(0, 10))
}

var timestamp = fetch_unix_timestamp();
var nocacheurl = url+"?t="+timestamp;

// the ajax call
xmlHttp.onreadystatechange=function(){
if(xmlHttp.readyState == 4 && xmlHttp.status == 200){
document.getElementById(divid).innerHTML=xmlHttp.responseText;
setTimeout(function(){refreshDivs(divid,secs,url);},secs*1000);
}
}
xmlHttp.open("GET",nocacheurl,true);
xmlHttp.send(null);
}

// LLamamos las funciones con los repectivos parametros de los DIVs que queremos refrescar.
window.onload = function startrefresh(){
refreshDivs('wrap1',2,'#');


}
</script>









<div id="col_6" class="col_6">
<a>Puntos del Partido</a><br><br>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th colspan="2">Game 1</th>
            <th colspan="2">Game 2</th>
            <th colspan="2">Game 3</th>
            <th colspan="2">Game 4</th>
            <th colspan="2">Game 5</th>
            <th colspan="2">Game 6</th>
            <th colspan="2">Game 7</th>            
            <th colspan="2">Game 8</th>
        </tr>
        <tr>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
        </tr>
        
    </thead>
    <tbody>
            <tr>
                <td><?php echo $this->escape($this->d->puntosjugadoruno1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno4); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos4); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno5); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos5); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno6); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos6); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno7); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos7); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno8); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos8); ?></td>
            </tr>
    </tbody>
</table>
</div>