

<script type="text/javascript">
    setTimeout ("redireccionar()", 10000);
    function redireccionar(){
        window.location="<?php echo $this->url(array('controller' => 'partido',
    'action' => 'mostrar'));
?>";
                       } 
</script>
<div class="col_6">
<a>Puntos del Partido</a><br><br>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th colspan="2">Game 1</th>
            <th colspan="2">Game 2</th>
            <th colspan="2">Game 3</th>
            <th colspan="2">Game 4</th>
            <th colspan="2">Game 5</th>
            <th colspan="2">Game 6</th>
            <th colspan="2">Game 7</th>            
            <th colspan="2">Game 8</th>
        </tr>
        <tr>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
            <th>Jugad1</th><th>Jugad2</th>
        </tr>
        
    </thead>
    <tbody>
            <tr>
                <td><?php echo $this->escape($this->d->puntosjugadoruno1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos1); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos2); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos3); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno4); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos4); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno5); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos5); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno6); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos6); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno7); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos7); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadoruno8); ?></td>
                <td><?php echo $this->escape($this->d->puntosjugadordos8); ?></td>
            </tr>
    </tbody>
</table>
</div>