<!DOCTYPE html>
<html>

  <head>
    <title>www</title> 
 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.css" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js"></script>
	<script type="text/javascript" src="http://dev.jtsage.com/cdn/datebox/latest/jquery.mobile.datebox.min.js"></script> 
	
	<link rel="stylesheet" type="text/css" href="http://dev.jtsage.com/cdn/datebox/latest/jquery.mobile.datebox.min.css" />
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" />
    </head>

<body> 
            <div data-role="header" data-position="inline" data-theme="b">    

                <a href="<?php echo $this->url(array('controller' => 'ejerciciosarealizar','action' => 'index'));
               ?>" data-icon="home" data-transition="flip">Home</a>
                <h3>
                    <?php echo $this->title; ?>
                </h3>
                <a href="prueba/prueba.html" data-icon="person" data-transition="flip">Prueba</a>
            </div>


            <div data-role="content">
              
                <?php echo $this->form; ?>
           
             
        </div>
    </body> 
    <div data-role="footer" data-theme="c">
        <h4>&copy; </h4>
    </div><!-- /footer -->

</html>