<!DOCTYPE html>
<html>

  <head>
    <title>www</title> 
 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.css" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js"></script>
	<script type="text/javascript" src="http://dev.jtsage.com/cdn/datebox/latest/jquery.mobile.datebox.min.js"></script> 
	
	<link rel="stylesheet" type="text/css" href="http://dev.jtsage.com/cdn/datebox/latest/jquery.mobile.datebox.min.css" />
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" />
    </head>

<body> 


<div data-role="page" id="login" data-title="Login">
    <div data-role="header" data-theme="c">
        <h1>Iniciar Sesi&oacute;n</h1>
        <a href="#home" data-icon="home" data-iconpos="notext" class="ui-btn-right"></a>
    </div><!-- /header -->
 
    <div data-role="content" data-theme="c">
    
        <form action="#" method="post" id="login">           
           		
	  <div data-role="collapsible-set">

	      <div data-role="collapsible" data-collapsed="false">
	      <h3>Game uno</h3>
	       <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>	          
	      </div>
	      
	      <div data-role="collapsible">
	      <h3>Game dos</h3>
		 
		<fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
		 
		 
	      </div>
	      <div data-role="collapsible">
	      <h3>Game tres</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	      <div data-role="collapsible">
	      <h3>Game cuatro</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	       <div data-role="collapsible" data-collapsed="true" >
	      <h3>Game quinto</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	      <div data-role="collapsible" >
	      <h3>Game sexto</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	       <div data-role="collapsible" >
	      <h3>Game septimo</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	       <div data-role="collapsible" >
	      <h3>Game octavo</h3>
	         <fieldset class="ui-grid-a">
		    <div class="ui-block-a">
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		       <label for="basic">Jugador uno:</label>
		       <input type="text" name="name" id="basic" value=""  />
		    </div>
		    <div class="ui-block-b">
		     <input type="radio" name="radio-choice-1" id="radio-mini-1" value="choice-4"  />
		     <label for="radio-choice-1">Jugado</label>

		   </div>	   
	      </fieldset>
	      </div>
	     
	    </div>
	      
        </form>
    </div><!-- /content -->
 
    <div data-role="footer" data-theme="c">
        <h4>&copy; </h4>
    </div><!-- /footer -->
</div><!-- /page login -->


</body> 
    <div data-role="footer" data-theme="c">
        <h4>&copy; </h4>
    </div><!-- /footer -->

</html>
