<script type="text/javascript" charset="utf-8">
    function confirmDelete(d) {var deleteArticle = confirm('Está seguro que desea eliminar la pareja?');
        if(deleteArticle){
            window.location.href = '<?php echo $this->url(array('controller' => 'pareja', 'action' => 'eliminar')); ?>'+'/_id/'+d;
        }
        return;
    }
</script>

<!--para agregar un nuevo juez-->
<div class="col_6">
<a href="<?php echo $this->url(array('controller' => 'pareja',
            'action' => 'crear')); ?>">Crear nueva Pareja</a>
	<h4>Parejas</h4>
<!--creo una tabla para mostrar los datos-->
<table class="sortable">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Jugador uno</th>
            <th>Jugador dos</th>
            <th>Acción</th>
    
        </tr>
    </thead>
    <tbody>
        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->datos as $d): ?>
            <!--           por cada fila, muestro sus datos -->
            <tr>
                <td><a href="<?php echo $this->url(array('controller' => 'pareja', 'action' => 'modificar', '_id' => $d->_id)); ?>"><?php echo $d->_id; ?></a></td>
                <!--                   enlace para borrar el album-->
                <td>
                <?php
                $datos1 = Application_Model_Jugador::find($d->jugadoruno);
                if($datos1=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos1->nombre);
                ?>
                </td>
                <td>
                <?php
                $datos2 = Application_Model_Jugador::find($d->jugadordos);
                if($datos2=="")
                    echo "Ninguno";
                else
                    echo $this->escape($datos2->nombre);
                ?>
                </td>
                
                <td><a href="<?php  echo $this->url(array('controller' => 'pareja', 'action' => 'modificar', '_id' => $d->_id)); ?>"><span title="Editar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/pencil.png" /></span></a>&nbsp;&nbsp;  
                    <a onclick="confirmDelete('<?php echo $d->_id; ?>')" >  <span title="Eliminar"><img class="imageCn1t1" src="../public/Icons/PNG/16px/minus.png" /></span></a> 
                </td>
            </tr>
            <!--    fin del for-->
        <?php endforeach; ?>
    </tbody>
</table>